package ru.tomilo.lib.mobile.core

/**
 * Все жанры, теги и служебные бейджи на экране — по-русски.
 * Ключ запроса в API не меняем, переводим только подпись.
 */
object GenreLabels {
    fun ru(raw: String?): String {
        val src = raw?.trim().orEmpty()
        if (src.isEmpty()) return ""
        keys(src).firstNotNullOfOrNull { MAP[it] }?.let { return it }
        if (hasCyrillic(src)) return titleRu(src)
        val words = keys(src).first()
        val parts = words.split(" ")
        if (parts.size > 1) {
            val translated = parts.map { MAP[it] ?: it }
            if (translated.any(::hasCyrillic)) return translated.joinToString(" ")
        }
        return titleRu(src)
    }

    fun ruOrHide(raw: String?): String? {
        val t = ru(raw)
        if (t.isBlank()) return null
        if (hasCyrillic(t) || t.any { it.isDigit() } || t.endsWith("+")) return t
        return null
    }

    fun type(raw: String?): String = ru(raw).ifBlank { "Тайтл" }

    fun status(raw: String?): String = ru(raw)

    fun age(limit: Int?): String = when (limit) {
        null -> ""
        0 -> "0+"
        else -> "$limit+"
    }

    private fun keys(src: String): List<String> {
        val spaced = src.lowercase()
            .replace('_', ' ')
            .replace('-', ' ')
            .replace('/', ' ')
            .replace(Regex("\\s+"), " ")
            .trim()
        return listOf(src.trim(), src.trim().lowercase(), spaced).distinct().filter { it.isNotEmpty() }
    }

    private fun hasCyrillic(s: String): Boolean = s.any { it in '\u0400'..'\u04FF' }

    private fun titleRu(s: String): String =
        s.lowercase().split(Regex("\\s+")).joinToString(" ") { w ->
            if (w.isEmpty()) w else w.replaceFirstChar { ch -> ch.titlecase() }
        }

    private val MAP = mapOf(
        "18+" to "18+",
        "action adventure" to "Боевик",
        "alternate universe" to "Альтернативная вселенная",
        "alternative present" to "Альтернативное настоящее",
        "ancient world" to "Древний мир",
        "animal companions" to "Животные компаньоны",
        "announced" to "Анонс",
        "publishing" to "Выходит",
        "ranobe" to "Ранобэ",
        "light novel" to "Ранобэ",
        "finished" to "Завершён",
        "oneshot" to "Ваншот",
        "one shot" to "Ваншот",
        "another world" to "Исекай",
        "another world memory" to "Память другого мира",
        "anthology" to "Антология",
        "anti hero" to "Антигерой",
        "arranged marriage" to "Брак по договорённости",
        "athletic body" to "Спортивное тело",
        "avant garde" to "Авангард",
        "big ass" to "Большая попка",
        "big breasts" to "Большая грудь",
        "big clit" to "Большой клитор",
        "big nipples" to "Большие соски",
        "big penis" to "Большой член",
        "boys love" to "Спокон",
        "brother and sister" to "Брат и сестра",
        "business suit" to "Деловой костюм",
        "canceled" to "Отменён",
        "cancelled" to "Отменён",
        "cat girl" to "Девушка-кошка",
        "cat wife" to "Кошка-жена",
        "character growth" to "Рост персонажа",
        "chinese dress" to "Китайская одежда",
        "comic" to "Комикс",
        "comics" to "Комикс",
        "complete" to "Завершён",
        "completed" to "Завершён",
        "cruel world" to "Жестокий мир",
        "cum in pussy" to "Вагинальный кремпай",
        "cute girls doing cute things" to "Милые девушки, делающие милые вещи",
        "dark skin" to "Тёмнокожие",
        "dark world" to "Мрачный мир",
        "demon girl" to "Демонесса",
        "dickgirl on female" to "Футанари на женщине",
        "double penetration" to "Двойное проникновение",
        "doujinshi" to "Додзинси",
        "draft" to "Черновик",
        "dropped" to "Брошено",
        "educational institution" to "Учебное заведение",
        "elderly protagonist" to "Старый Главный герой",
        "elements of humor" to "Элементы юмора",
        "evil spirit" to "Злой дух",
        "fantasy romance" to "Романтика",
        "fantasy world" to "Фэнтезийный мир",
        "favorite" to "Избранное",
        "favorites" to "Избранное",
        "favourite" to "Избранное",
        "female harem" to "Гарем девушек",
        "female idol" to "Идол",
        "female protagonist" to "Главная героиня",
        "finished" to "Завершён",
        "free" to "Бесплатно",
        "gag humor" to "Гэг-юмор",
        "game elements" to "Игровые элементы",
        "gender bending" to "Гендерная интрига",
        "gender change" to "Смена пола",
        "gender intrigue" to "Гендерная интрига",
        "gender morph" to "Смена пола",
        "girls love" to "Сёдзе-ай",
        "god protagonist" to "Главный герой бог",
        "group sex" to "Групповой Секс",
        "hentai themes" to "Хентайные Темы",
        "heroic fantasy" to "Героическое фэнтези",
        "hiatus" to "Пауза",
        "hidden" to "Скрыт",
        "hiding identity" to "Скрытие личности",
        "high stakes game" to "Игра с высокими ставками",
        "hot" to "Хит",
        "huge penis" to "Огромный член",
        "human on furry" to "Человек на фурри",
        "isekai world" to "Попадание в другой мир",
        "kingdom management" to "Управление территорией",
        "legendary weapon" to "Легендарное оружие",
        "level up" to "Повышение уровня",
        "light novel" to "Ранобэ",
        "long hair" to "Длинные волосы",
        "long strip" to "Вебтун",
        "longstrip" to "Вебтун",
        "lots of sperm" to "Много семени",
        "love" to "Сёнен-ай",
        "love polygon" to "Любовный многоугольник",
        "magic academy" to "Магическая академия",
        "magical creatures" to "Магические существа",
        "mahou shoujo" to "Девочки-волшебницы",
        "main cast" to "Основной каст",
        "male harem" to "Мужской гарем",
        "male idol" to "Идол",
        "male protagonist" to "Главный герой мужчина",
        "manga" to "Манга",
        "manhua" to "Маньхуа",
        "manhwa" to "Манхва",
        "martial arts" to "Боевые искусства",
        "masked face" to "Лицо в маске",
        "mature female" to "Зрелые женщины",
        "mental illness" to "Психические отклонения",
        "middle ages" to "Средневековье",
        "middle school" to "Средняя школа",
        "mind control" to "Промывание мозгов",
        "mmf threesome" to "ММЖ Втроём",
        "monster girl" to "Монстродевушка",
        "monster girls" to "Девушки-монстры",
        "moving between worlds" to "Перемещение между мирами",
        "new" to "Новое",
        "no panties" to "Без трусиков",
        "non human protagonist" to "Главный герой не человек",
        "normal sex" to "Обычный секс",
        "novel" to "Новелла",
        "nsfw" to "18+",
        "office lady" to "Офисная леди",
        "office workers" to "Офисные работники",
        "offline" to "Офлайн",
        "ojou sama" to "Богатая леди",
        "old man" to "Старик",
        "one shot" to "Ваншот",
        "oneshot" to "Ваншот",
        "ongoing" to "Выходит",
        "op mc" to "ГГ имба",
        "oppai loli" to "Лоли с грудью",
        "otaku culture" to "Культура Отаку",
        "overpowered protagonist" to "Всесильный главный герой",
        "paid" to "Платно",
        "pause" to "Пауза",
        "paused" to "Пауза",
        "planned" to "В планах",
        "post apocalyptic" to "Постапокалипсис",
        "power ranks" to "Ранги силы",
        "power struggle" to "Борьба за власть",
        "premium" to "Премиум",
        "primarily adult cast" to "В основном взрослые персонажи",
        "primarily animal cast" to "В основном животные",
        "primarily female cast" to "В основном женщины",
        "primarily male cast" to "В основном мужчины",
        "primarily teen cast" to "В основном подростки",
        "psychological horror" to "Психологический ужас",
        "public place" to "Общественное место",
        "published" to "Опубликован",
        "reading" to "Читаю",
        "reverse harem" to "Обратный гарем",
        "rom com" to "Ромком",
        "romcom" to "Ромком",
        "royal affairs" to "Королевские дела",
        "saving the world" to "Спасение мира",
        "school life" to "Школьная жизнь",
        "school uniform" to "Школьная форма",
        "school uniform for girls" to "Школьная форма мальчиков",
        "sci fi" to "Научная фантастика",
        "science fiction" to "Научная фантастика",
        "secondary school" to "Старшая школа",
        "sentient races" to "Разумные расы",
        "sex toys" to "Секс игрушки",
        "shonen ai" to "Спокон",
        "shoujo ai" to "Сёдзё-ай",
        "shounen ai" to "Сёнэн-ай",
        "slice of life" to "Повседневность",
        "smart protagonist" to "Умный главный герой",
        "snake girl" to "Девушка-змея",
        "steel arms" to "Холодное оружие",
        "stomach deformation" to "Деформация живота",
        "stupid protagonist" to "Тупой Главный герой",
        "tall girl" to "Высокая девушка",
        "tall man" to "Высокий мужчина",
        "team sport" to "Командный спорт",
        "territory management" to "Управление территорией",
        "time manipulation" to "Манипуляция временем",
        "time travel" to "Путешествия во времени",
        "tone changes" to "Изменения тона",
        "traditional games" to "Традиционные игры",
        "transported to another world" to "Исекай",
        "unusual pupils" to "Необычные зрачки",
        "upcoming" to "Скоро",
        "urban fantasy" to "Городское фэнтези",
        "video games" to "Видеоигры",
        "virtual reality" to "Виртуальная реальность",
        "visual arts" to "Рисование",
        "visual humor" to "Гэг-юмор",
        "weak mc" to "ГГ слабый",
        "webtoon" to "Вебтун",
        "webtoons" to "Вебтун",
        "with a plot" to "С Сюжетом",
        "working life" to "Работа",
        "world conquest" to "Завоевание мира",
        "world war ii" to "Вторая мировая война",
        "wuxia" to "Уся",
        "x ray" to "X-Ray",
        "xuanhuan" to "Сюаньхуань",
        "young protagonist" to "Молодой Главный герой",
        "боевое искусство" to "Боевик",
        "боевые искусства" to "Боевые искусства",
        "борьба за власть" to "Борьба за власть",
        "в основном взрослые персонажи" to "В основном взрослые персонажи",
        "визуальный юмор" to "Гэг-юмор",
        "виртуальная реальность" to "Виртуальная реальность",
        "всесильный главный герой" to "Всесильный главный герой",
        "гарем девушек" to "Гарем девушек",
        "гг имба" to "ГГ имба",
        "гг слабый" to "ГГ слабый",
        "гендерный морф" to "Смена пола",
        "главная героиня" to "Главная героиня",
        "главный герой мужчина" to "Главный герой мужчина",
        "для взрослых" to "Сейнен",
        "для девочек" to "Сёдзе",
        "для мальчиков" to "Сёнэн",
        "ежедневная жизнь" to "Повседневность",
        "жестокий мир" to "Жестокий мир",
        "животные компаньоны" to "Животные компаньоны",
        "зрелые темы" to "Зрелые темы",
        "игровые элементы" to "Игровые элементы",
        "изобразительное искусство" to "Рисование",
        "китайская манга" to "Маньхуа",
        "конец света" to "Апокалиптический",
        "корейская манга" to "Манхва",
        "лайт новелла" to "Лайт-новелла",
        "любовный треугольник" to "Любовный многоугольник",
        "любовь девочек" to "Сёдзе-ай",
        "любовь мальчиков" to "Сёнен-ай",
        "магическая академия" to "Магическая академия",
        "магические существа" to "Магические существа",
        "манипуляция временем" to "Манипуляция временем",
        "махо сёдзё" to "Девочки-волшебницы",
        "научная фантастика" to "Научная фантастика",
        "обратный гарем" to "Обратный гарем",
        "память другого мира" to "Память другого мира",
        "повышение уровня" to "Повышение уровня",
        "попадание в другой мир" to "Попадание в другой мир",
        "путешествие в другой мир" to "Исекай",
        "путешествие во времени" to "Манипуляция временем / Путешествия",
        "путешествия во времени" to "Путешествия во времени",
        "разумные расы" to "Разумные расы",
        "ранги силы" to "Ранги силы",
        "скрытие личности" to "Скрытие личности",
        "смертельная игра" to "Игра с высокими ставками",
        "стимуляция грудью" to "Пайзури",
        "сёдзё ай" to "Сёдзё-ай",
        "сёнэн ай" to "Сёнэн-ай",
        "умный главный герой" to "Умный главный герой",
        "управление территорией" to "Управление территорией",
        "школьная жизнь" to "Повседневность",
        "элементы рпг" to "Игровые элементы",
    )
}
